/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `en_HK` locale.
 *
 * - Language: English (Hong Kong)
 * - Endonym: English (Hong Kong)
 */
const en_HK: LocaleDefinition = {
  location,
  metadata,
};

export default en_HK;
