/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `cy` locale.
 *
 * - Language: Welsh
 * - Endonym: Cymraeg
 */
const cy: LocaleDefinition = {
  location,
  metadata,
};

export default cy;
