/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `sr_RS_latin` locale.
 *
 * - Language: Serbian (Serbia, Latin)
 * - Endonym: srpski (Srbija, latinica)
 */
const sr_RS_latin: LocaleDefinition = {
  location,
  metadata,
};

export default sr_RS_latin;
