/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `en_AU` locale.
 *
 * - Language: English (Australia)
 * - Endonym: English (Australia)
 */
const en_AU: LocaleDefinition = {
  location,
  metadata,
};

export default en_AU;
