/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `he` locale.
 *
 * - Language: Hebrew
 * - Endonym: עברית
 */
const he: LocaleDefinition = {
  location,
  metadata,
};

export default he;
