/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `it` locale.
 *
 * - Language: Italian
 * - Endonym: Italiano
 */
const it: LocaleDefinition = {
  location,
  metadata,
};

export default it;
