/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `hy` locale.
 *
 * - Language: Armenian
 * - Endonym: Հայերեն
 */
const hy: LocaleDefinition = {
  location,
  metadata,
};

export default hy;
