/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `lv` locale.
 *
 * - Language: Latvian
 * - Endonym: latviešu valoda
 */
const lv: LocaleDefinition = {
  location,
  metadata,
};

export default lv;
