/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `en_CA` locale.
 *
 * - Language: English (Canada)
 * - Endonym: English (Canada)
 */
const en_CA: LocaleDefinition = {
  location,
  metadata,
};

export default en_CA;
