/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `en_US` locale.
 *
 * - Language: English (United States)
 * - Endonym: English (United States)
 */
const en_US: LocaleDefinition = {
  location,
  metadata,
};

export default en_US;
