/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `sk` locale.
 *
 * - Language: Slovak
 * - Endonym: slovenčina
 */
const sk: LocaleDefinition = {
  location,
  metadata,
};

export default sk;
