/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `ka_GE` locale.
 *
 * - Language: Georgian (Georgia)
 * - Endonym: ქართული (საქართველო)
 */
const ka_GE: LocaleDefinition = {
  location,
  metadata,
};

export default ka_GE;
