/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `cs_CZ` locale.
 *
 * - Language: Czech (Czechia)
 * - Endonym: čeština (Česká republika)
 */
const cs_CZ: LocaleDefinition = {
  location,
  metadata,
};

export default cs_CZ;
