/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `az` locale.
 *
 * - Language: Azerbaijani
 * - Endonym: azərbaycan dili
 */
const az: LocaleDefinition = {
  location,
  metadata,
};

export default az;
