/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `fr` locale.
 *
 * - Language: French
 * - Endonym: Français
 */
const dk: LocaleDefinition = {
  location,
  metadata,
};

export default dk;
