/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `ur` locale.
 *
 * - Language: Urdu
 * - Endonym: اردو
 */
const ur: LocaleDefinition = {
  location,
  metadata,
};

export default ur;
