/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `nl_BE` locale.
 *
 * - Language: Dutch (Belgium)
 * - Endonym: Nederlands (België)
 */
const nl_BE: LocaleDefinition = {
  location,
  metadata,
};

export default nl_BE;
