/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `ne` locale.
 *
 * - Language: Nepali
 * - Endonym: नेपाली
 */
const ne: LocaleDefinition = {
  location,
  metadata,
};

export default ne;
