/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `ar` locale.
 *
 * - Language: Arabic
 * - Endonym: اَلْعَرَبِيَّةُ
 */
const ar: LocaleDefinition = {
  location,
  metadata
};

export default ar;
