/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `ja` locale.
 *
 * - Language: Japanese
 * - Endonym: 日本語
 */
const ja: LocaleDefinition = {
  location,
  metadata,
};

export default ja;
