/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `en_GH` locale.
 *
 * - Language: English (Ghana)
 * - Endonym: English (Ghana)
 */
const en_GH: LocaleDefinition = {
  location,
  metadata,
};

export default en_GH;
