/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `af_ZA` locale.
 *
 * - Language: Afrikaans (South Africa)
 * - Endonym: Afrikaans (Suid-Afrika)
 */
const af_ZA: LocaleDefinition = {
  location,
  metadata
};

export default af_ZA;
