/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import { Faker } from '../faker';
import base from '../locales/base';
import en from '../locales/en';
import si from '../locales/si';

/**
 * The faker instance for the `fr` locale.
 *
 * - Language: French
 * - Endonym: Français
 *
 * This instance uses the following locales internally (in descending precedence):
 *
 * - `fr`
 * - `en`
 * - `base`
 */
export const faker = new Faker({
  locale: [si, en, base],
});
