/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `es` locale.
 *
 * - Language: Spanish
 * - Endonym: Español
 */
const es: LocaleDefinition = {
  location,
  metadata,
};

export default es;
