/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `sv` locale.
 *
 * - Language: Swedish
 * - Endonym: Svenska
 */
const sv: LocaleDefinition = {
  location,
  metadata,
};

export default sv;
