/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `hr` locale.
 *
 * - Language: Croatian
 * - Endonym: Hrvatski
 */
const hr: LocaleDefinition = {
  location,
  metadata,
};

export default hr;
