/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `dv` locale.
 *
 * - Language: Maldivian
 * - Endonym: ދިވެހި
 */
const dv: LocaleDefinition = {
  location,
  metadata,
};

export default dv;
