/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `pt_BR` locale.
 *
 * - Language: Portuguese (Brazil)
 * - Endonym: Português (Brasil)
 */
const pt_BR: LocaleDefinition = {
  location,
  metadata,
};

export default pt_BR;
