/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `base` locale.
 *
 * The base locale contains data that is shared across all locales such as ISO codes, time zones, and more.
 */
const base: LocaleDefinition = {
  location,
  metadata,
};

export default base;
