/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `es_MX` locale.
 *
 * - Language: Spanish (Mexico)
 * - Endonym: Español (México)
 */
const es_MX: LocaleDefinition = {
  location,
  metadata,
};

export default es_MX;
