/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `fr_LU` locale.
 *
 * - Language: French (Luxembourg)
 * - Endonym: Français (Luxembourg)
 */
const fr_LU: LocaleDefinition = {
  location,
  metadata,
};

export default fr_LU;
