/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `ro` locale.
 *
 * - Language: Romanian
 * - Endonym: Română
 */
const ro: LocaleDefinition = {
  location,
  metadata,
};

export default ro;
