/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `vi` locale.
 *
 * - Language: Vietnamese
 * - Endonym: Tiếng Việt
 */
const vi: LocaleDefinition = {
  location,
  metadata,
};

export default vi;
