/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import country_code from './country_code';

const location: LocationDefinition = {
  country_code,
};

export default location;
