/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `zh_TW` locale.
 *
 * - Language: Chinese (Taiwan)
 * - Endonym: 中文 (臺灣)
 */
const zh_TW: LocaleDefinition = {
  location,
  metadata,
};

export default zh_TW;
