/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocationDefinition } from '../../..';
import city_name from './city_name';
import city_pattern from './city_pattern';
import postcode from './postcode';
import street_name from './street_name';
import street_pattern from './street_pattern';
import state_abbr from "./state_abbr";
import street_address from "./street_address";

const location: LocationDefinition = {
  city_name,
  city_pattern,
  postcode,
  street_name,
  street_pattern,
  state_abbr,
  street_address,
};

export default location;
