/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `el` locale.
 *
 * - Language: Greek
 * - Endonym: Ελληνικά
 */
const el: LocaleDefinition = {
  location,
  metadata,
};

export default el;
