/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `da` locale.
 *
 * - Language: Danish
 * - Endonym: Dansk
 */
const da: LocaleDefinition = {
  location,
  metadata,
};

export default da;
