/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `de` locale.
 *
 * - Language: German
 * - Endonym: Deutsch
 */
const de: LocaleDefinition = {
  location,
  metadata,
};

export default de;
