/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `th` locale.
 *
 * - Language: Thai
 * - Endonym: ไทย
 */
const th: LocaleDefinition = {
  location,
  metadata,
};

export default th;
