/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `en_ZA` locale.
 *
 * - Language: English (South Africa)
 * - Endonym: English (South Africa)
 */
const en_ZA: LocaleDefinition = {
  location,
  metadata,
};

export default en_ZA;
