/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `tr` locale.
 *
 * - Language: Turkish
 * - Endonym: Türkçe
 */
const tr: LocaleDefinition = {
  location,
  metadata,
};

export default tr;
