/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `pt_PT` locale.
 *
 * - Language: Portuguese (Portugal)
 * - Endonym: Português (Portugal)
 */
const pt_PT: LocaleDefinition = {
  location,
  metadata,
};

export default pt_PT;
