/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import metadata from './metadata';

/**
 * The locale data for the `en_BORK` locale.
 *
 * - Language: English (Bork)
 * - Endonym: English (Bork)
 */
const en_BORK: LocaleDefinition = {
  metadata,
};

export default en_BORK;
