/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */
import type { LocaleDefinition } from '../..';
import location from './location';
import metadata from './metadata';

/**
 * The locale data for the `ru` locale.
 *
 * - Language: Russian
 * - Endonym: Русский
 */
const ru: LocaleDefinition = {
  location,
  metadata,
};

export default ru;
